- name: Deploy alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_config: "{{ lookup('ansible.builtin.template', ansible_parent_role_paths[0] + '/templates/config.alloy.j2' ) }}"