---
- name: NAS Setup
  hosts: nas
  gather_facts: true
  become: true
  roles:
    - role: common
    - role: zfs
    - role: libvirt
    - role: cockpit
      vars:
        fileShare: true
        zfs: true
        machines: true